### ISSUE TITLE
SCA + PaymentIntent

### ISSUE THREAD

**Issue by nkmnz** [Cl3MM/vue-stripe-better-elements#2]
Hey, thanks a lot for implementing IBAN Payments! That's a huge help. But now I'm stuck at using the new Stripe PaymentIntents API instead of creating token or source. Vue-stripe-elements uses handleCardPayment in order to charge the intent. Do you have any suggestion on how to implement this with vue-stripe-better-elements?

**Comment by Cl3MM** [comment]
Hey, thanks for your interest in this fork! It's always nice to have some feedback (and even better when it's a positive one ;) )

I wasn't aware of the new API, but I'll look into it and try to update the package as soon as possible.

From what I've seen in the [migration guide](https://stripe.com/docs/payments/payment-intents/migration#elements), it should just be a matter of switching from `stripe.createToken` to `createPaymentMethod` but maybe there is more to it.

Have you already looked into the migration process? Do you have any suggestion?

**Comment by nkmnz** [comment]
I think we have first to create the paymentIntent on the backend instead of using `createToken/createSource` and then use  [`stripe.confirmSepaDebitPayment`](https://stripe.com/docs/stripe-js/reference#stripe-confirm-sepa-debit-payment) for sepa and [`stripe.confirmCardPayment`](https://stripe.com/docs/stripe-js/reference#stripe-confirm-card-payment) for credit cards from the client. But adding these methods to `stripeElements.js` didn't work out for me...
